### ISSUE TITLE
Running demo yields error: "Cannot find module 'ramda'"

### ISSUE THREAD

**Issue by justinmayer** [runkitdev/runkit-demo#1]
### Problem

Running demo yields an unrecoverable error: <details><summary>[Tap to show traceback]</summary>
$ demokit runkit-demo-master/script.js

GVA info: Successfully connected to the Intel plugin, offline Gen9
{ Error: Cannot find module 'ramda'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/local/lib/node_modules/demokit/electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/usr/local/lib/node_modules/demokit/electron/demokit-run.js:28:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at Module.require (/usr/local/lib/node_modules/demokit/electron/demokit-run.js:58:34)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Downloads/runkit-demo-master/comment.js:2:20)
    at Module._compile (module.js:556:32)
    at loader (/usr/local/lib/node_modules/demokit/electron/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/demokit/electron/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at Module.require (/usr/local/lib/node_modules/demokit/electron/demokit-run.js:58:34) code: 'MODULE_NOT_FOUND' }
</details>

### Steps to reproduce

1. Install Node 4.x LTS on macOS Sierra via: `brew install homebrew/versions/node4-lts`
2. Install Demokit via: `npm install --global demokit`
3. Download current runkit-demo master (9db4352) as .zip file and extract
4. `demokit runkit-demo-master/script.js`

### Environment

* macOS Sierra 10.12
* Node 4.6.1
* NPM 2.15.9

**Comment by 0joshuaolson1** [comment]
I've had this problem with other libraries on runkit.com itself, when the real error is code unrelated to a require.

**Comment by dmail** [comment]
So it's related to what?
